services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        
    Application\Controller\:
        resource: '../../../src/Application/Controller/*'
        
    controller.landing:
        alias: 'Application\Controller\Landing'

    controller.admin:
        alias: 'Application\Controller\AdminController'

    controller.tags:
        alias: 'Application\Controller\TagController'

    controller.supplements:
        alias: 'Application\Controller\SupplementController'

    controller.products:
        alias: 'Application\Controller\ProductController'

    controller.statistics:
        alias: 'Application\Controller\StatisticController'

    controller.monolog:
        alias: 'Application\Controller\MonologController'

